### ISSUE TITLE
Connects and Plugs inside WebApp are insecure

### ISSUE THREAD

**Issue by vhbmsp** [pintorafael/alpha#11]
If you put plugs config files inside WebApp like the MySQL.plug they are easily reached from www.example.com/plugs/MySQL.plug and are world readable in plain text.

Anyone knowing that a site / API uses your framework can easily search for this kind of files.

Move important files like config files that can have passwords outside document root / WebApp folder.

**Comment by pintorafael** [comment]
Hi Vasco, how are you?

I have been implementing the functionality stuff and wrongly misplaced the **index.php** and set the document root to **webapp** instead of **htdocs**, but i have now fixed it. 

Thank you very much for pointing that out. If you have any more suggestions, please fill free to create issues or contact me.

Best regards,
rafael

**Comment by vhbmsp** [comment]
Btw, deves actualizar também o sample conf do vhost!

Abraço,

Vasco
Em 22/02/2015 22:45, "Rafael Pinto" <notifications@github.com> escreveu:
